services:
  nestjs_api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
      - cache
    ports:
      - '${API_PORT}:${API_PORT}'
    environment:
      - PORT=${API_PORT}
      - NODE_ENV=${API_ENV}
    volumes:
      - ./src:/app/src
  postgres_db:
    image: postgres
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PORT=${DATABASE_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
  cache:
    image: redis
    restart: always
    ports:
      - '${CACHE_PORT}:${CACHE_PORT}'
    environment:
      - REDIS_PORT=${CACHE_PORT}
      - REDIS_PASSWORD=${CACHE_PASSWORD}
    volumes:
      - cache:/data

volumes:
  pgdata:
  cache:
