PATCH http://localhost:3000/questions/
Content-Type: application/json

{
  "id": "fbad309a-c386-4bf7-b8a9-9a3c3939d7cb",
  "title": "What's new with NestJS With TypeScript",
  "tags": ["374fb32e-417a-4497-b677-f57e4292c76e","8823fc8e-9d49-43da-ae60-735fe1949624"]
}