POST http://localhost:3000/questions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MzIzNjRlMi1hOGRiLTQ0OWMtOTdjOS0xN2YyNjFjZDc3MWQiLCJlbWFpbCI6Im1hcmtAaG9sZGVuLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM0MDgyNzk5LCJleHAiOjE3MzQwODYzOTksImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.waPhn8msZWTcLZis15hCmIMNoa2R60hfE9NNrAclXFw

{
  "rating": 0,
  "title": "New question TypeOrm 3",
  "description": "Question description for test with user from request",
  "tags": ["69341744-a9ed-4646-b9cd-754127a6524a","3605b855-b433-445d-832d-7272ce7d57c3"]
}
