GET http://localhost:3000/questions/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MzIzNjRlMi1hOGRiLTQ0OWMtOTdjOS0xN2YyNjFjZDc3MWQiLCJlbWFpbCI6Im1hcmtAaG9sZGVuLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM0MDg1MDI5LCJleHAiOjE3MzQwODg2MjksImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.hhDhUElJnxAnD02IIFWmZowKolKMnvqCaIdFv5gqVyc