GET http://localhost:3000/questions/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmZjg3ZDRkYS0zZTBmLTQ0NGQtOWIzZS0yZTEzNzQ4YzA3YjgiLCJlbWFpbCI6Im1hcmtAaG9sZGVuLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczMzQ5ODQ1NSwiZXhwIjoxNzMzNTAyMDU1LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.StLbmRSO3_vcrPxPKUC7W5rAVcvLQ0SzEiYTNXra7Vk