DELETE http://localhost:3000/questions/
  ?id=b6ea1a87-4298-4a68-be0a-a966f01386fe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MzIzNjRlMi1hOGRiLTQ0OWMtOTdjOS0xN2YyNjFjZDc3MWQiLCJlbWFpbCI6Im1hcmtAaG9sZGVuLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQxNjg0MzA3LCJleHAiOjE3NDE2ODc5MDcsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.EFI7CpL-njI-D7Vmvn_860jGVpL8Psd29BKLhh9iXTw
