POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmZjg3ZDRkYS0zZTBmLTQ0NGQtOWIzZS0yZTEzNzQ4YzA3YjgiLCJlbWFpbCI6Im1hcmtAaG9sZGVuLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzMzOTEzMjk4LCJleHAiOjE3MzM5MTY4OTgsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.pOKdR-ndWD9eyi0y26Z7aFZ-53M2sAjdpkGVm9Zkego

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmZjg3ZDRkYS0zZTBmLTQ0NGQtOWIzZS0yZTEzNzQ4YzA3YjgiLCJpYXQiOjE3MzM5MTMyOTgsImV4cCI6MTczMzk5OTY5OCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.VLaYWfGNXQMr4vKBaDAx579Iy5nnaPhH_lm3OzI-8Xs"
}