POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MzIzNjRlMi1hOGRiLTQ0OWMtOTdjOS0xN2YyNjFjZDc3MWQiLCJlbWFpbCI6Im1hcmtAaG9sZGVuLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzMzOTkzMzA5LCJleHAiOjE3MzM5OTY5MDksImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.BI8rd2rqKdNeq5MSg9ew2NW7FEfVHOfD127cFvarTCI

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MzIzNjRlMi1hOGRiLTQ0OWMtOTdjOS0xN2YyNjFjZDc3MWQiLCJpYXQiOjE3MzM5OTMzMDksImV4cCI6MTczNDA3OTcwOSwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.Vwp_LHgKKclF81gBISfQcWGrSkOqoXM7pMWg3H8zLkQ"
}