POST http://localhost:3000/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MzIzNjRlMi1hOGRiLTQ0OWMtOTdjOS0xN2YyNjFjZDc3MWQiLCJlbWFpbCI6Im1hcmtAaG9sZGVuLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM0MDgxNTE3LCJleHAiOjE3MzQwODUxMTcsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.2b9jGc0_5RdZW7SQY7CQ-gnlCVnjbxTDJtguy-f3vFU

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MzIzNjRlMi1hOGRiLTQ0OWMtOTdjOS0xN2YyNjFjZDc3MWQiLCJpYXQiOjE3MzQwODE1MTcsImV4cCI6MTczNDE2NzkxNywiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.NYlZ4oIzJwSo2YR21vA5QFwapFuH_ez4Ur4L0ldhFFA"
}