GET http://localhost:3000/tags/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmZjg3ZDRkYS0zZTBmLTQ0NGQtOWIzZS0yZTEzNzQ4YzA3YjgiLCJlbWFpbCI6Im1hcmtAaG9sZGVuLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzMzNTAyODk0LCJleHAiOjE3MzM1MDY0OTQsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.cvBwec-3FiB5Lc55jyp5Y__CaAHGc2K3T3mRbYGD7Dg