GET http://localhost:3000/tags/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhOTU4OTk2NS1jOTYyLTRjY2QtYTM2Ny0yMGY1NGRlNGQwMGYiLCJlbWFpbCI6ImFuZ2VsaW5hQGpvbGllLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczNDA4MzcwNywiZXhwIjoxNzM0MDg3MzA3LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.XFcKUEes477UjC_CIunvYv3KWoeiUonfh-uK9sENJ5g